### ISSUE TITLE
Don't be so nasty

### ISSUE THREAD

**Issue by nihgwu** [nihgwu/react-native-sudoku#2]
I open sourced this sudoku game but someone cloned to AppStore.

**Mine**

[AppStore](https://itunes.apple.com/app/id1138612488)
[Yingyongbao](http://a.app.qq.com/o/simple.jsp?pkgname=com.liteneo.sudoku)

**Clone**

[AppStore](https://itunes.apple.com/app/id1157001386)
[Google Play](https://play.google.com/store/apps/details?id=com.abbasbourji.sudokutrue)

Sudoku is the only game I play on mobile, so I made this app for fun, it's simple and pure, without any redundant functions. Several days ago I released a new version to add I18N support, then I searched 'sudoku' on AppStore to test but find this clone app.

The clone app simply changes the board color, translates Chinese to English, and adds ADs which make my really sad, the menus are unaligned too, really bad user experience.

I know I'm using the MIT license, so I can do nothing about that, but I still feel sick on this, as I've released it on AppStore already, he changed nothing but adding ADs and trying to pretend he developed the app by himself.

**Comment by AbbasEl-Bourji** [comment]
hello nihgwu ,
you have write in you license, every body can use you Game and Publish it. and I don't have cloned you Game, because you say everybody can publish it.
and if you are felling sick then tell me and I take out the Game from Apple and Play Store.

thank & best regards

**Comment by nihgwu** [comment]
I know the license ensure you can do anything you want with this project. I won't complain about that. It's would be awesome to make a better or more complex one or other things using my codes, but what you do is simply add ADs to reduce the experience, and disguise you made it from scratch in your description, I've said it in the original lines.

There is already  a sudoku game with exactly the same features, and I made it for fun, then what's your point to release yours to the store again?

There is a joke in our community, "You cloned my project without even a star".

**Comment by AbbasEl-Bourji** [comment]
first your app is on Chinese language, and a lot of people don't know Chinese, and I have translate it to English to give change to another users to use it.
and I don't say in description I have this game from scratch make.
and about the stars I have today make account in Github and no I can make Stars.

now say for me what you want ? do you want from me to add your project link with your name in the description ?
or you want from me to take the game down ?

say for me what you want. because what I try to make it to give change to people to play this game.

**Comment by nihgwu** [comment]
You are still missing my point, if you just want to make a chance for another people to play this game, why you added ADs and write such a long description? Besides I've pointed out that I'll add the I18N support in the README and I finished it right the day you release yours to the store.

I write this with no expectation, you have the right to do anything, and I have the right to create this issue.

**Comment by AbbasEl-Bourji** [comment]
I need to right long description to explain the users about the Game. And what feature in this game. And about the ADs
 It's nothing because the user that used this Game it's only 54 it's nothing. i don't need your game for given Money. My App have 310 000 download and I don't need you Game. Right now I don't have time to add new feature in your game. But if I have time I want to add multi And differents Levels and all Languages. And then can all people play this game.

**Comment by AbbasEl-Bourji** [comment]
If you want we can working together to make many Apps. i don't have a lot of free time to make it alone. If you want we can working as team. And I give you money

**Comment by AbbasEl-Bourji** [comment]
Hello, Please go to Play Store and update the App, in the new update
version do you can download photos, videos and documents. If you update the
App you DON’T need to rescan the QR code again!  And if you have android
version 5.0 and up then the size of the app is after the update only 9 mb.
Please give us 5 stars and a good review my friend. Have fun with the App !
